name: "Refresh jdk26 from Upstream"
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
env:
  UPSTREAM_REMOTE: https://github.com/openjdk/jdk26u.git
  UPSTREAM_LEYDEN: https://github.com/openjdk/leyden.git
  LOCAL_BRANCH: develop
  LOCAL_LEYDEN: leyden
  
permissions:
  contents: write
  
jobs:
    refresh-jdk:
        runs-on: ubuntu-latest
        name: "Update Corretto-26"
        if: github.repository_owner == 'corretto'
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                ref: ${{ env.LOCAL_BRANCH }}
                
            - name: "Configure the user"
              run: |
                git config user.email "no-reply@amazon.com"
                git config user.name "corretto-github-robot"
                
            - name: "Merge openjdk/jdk26u:master to the corretto-26:develop"
              run: |
                git fetch $UPSTREAM_REMOTE master || exit 1
                git merge -m "Merge upstream-jdk" FETCH_HEAD
                
            - name: "Update Corretto version"
              shell: bash
              run: bash ./.github/scripts/update-version.sh $UPSTREAM_REMOTE
            - name: "Push to the corretto-26"
              run: git push origin $LOCAL_BRANCH